import locale
from PyQt6.QtCore import QLocale

TRANSLATIONS = {
    "en": {
        "todo": "To Do",
        "doing": "In Progress",
        "done": "Completed",
        "low": "Low",
        "medium": "Medium",
        "high": "High",
        "work": "WORK",
        "break": "BREAK",
        "add_task": "Add Task",
        "edit_task": "Edit Task",
        "title": "Title",
        "description": "Description",
        "priority": "Priority",
        "tags_label": "Tags (comma separated)",
        "tags_placeholder": "e.g. ui, bug, code",
        "title_empty_warning": "Title field cannot be empty.",
        "warning": "Warning",
        "cancel": "Cancel",
        "save": "Save",
        "move_back": "Move Back",
        "move_forward": "Move Forward",
        "edit": "Edit",
        "delete": "Delete",
        "add": "Add",
        "focus_timer": "Focus Timer",
        "start": "Start",
        "pause": "Pause",
        "reset": "Reset",
        "work_btn": "25m Work",
        "break_short_btn": "5m Break",
        "break_long_btn": "15m Break",
        "running": "Running",
        "resume": "Resume",
        "congrats": "Congratulations!",
        "work_done_msg": "Your focus session is completed. Time for a break!",
        "break_done_title": "Break Finished",
        "break_done_msg": "Your break is over. Ready to focus again?",
        "app_title": "AuraTask",
        "total_focus_time": "Total Focus Time",
        "completed_pomodoros": "Completed Pomodoros",
        "last_7_days": "Last 7 Days Focus Chart (Minutes)",
        "task_board": "📋 Task Board",
        "analytics": "📈 Productivity Analytics",
        "app_subtitle": "Personal Focus & Task Manager",
        "summary_stats": "Summary Stats",
        "today_focus": "Today's Focus: {} min",
        "total_tasks": "Total Tasks: {}",
        "delete_title": "Delete Task",
        "delete_confirm": "Are you sure you want to permanently delete this task?",
        "clear_completed": "Clear Completed",
        "all_priorities": "All Priorities",
        "filter_priority": "Filter:",
        "search_placeholder": "🔍 Search tasks...",
        "min": "min",
        "sessions": "Sessions",
        "m": "m" # Chart axis label
    },
    "tr": {
        "todo": "Yapılacak",
        "doing": "Yapılıyor",
        "done": "Tamamlandı",
        "low": "Düşük",
        "medium": "Orta",
        "high": "Yüksek",
        "work": "ÇALIŞMA",
        "break": "MOLA",
        "add_task": "Görev Ekle",
        "edit_task": "Görevi Düzenle",
        "title": "Başlık",
        "description": "Açıklama",
        "priority": "Öncelik",
        "tags_label": "Etiketler (virgülle ayırın)",
        "tags_placeholder": "örn: arayüz, hata, kod",
        "title_empty_warning": "Başlık alanı boş bırakılamaz.",
        "warning": "Uyarı",
        "cancel": "İptal",
        "save": "Kaydet",
        "move_back": "Geri Al",
        "move_forward": "İlerlet",
        "edit": "Düzenle",
        "delete": "Sil",
        "add": "Ekle",
        "focus_timer": "Odak Zamanlayıcısı",
        "start": "Başlat",
        "pause": "Duraklat",
        "reset": "Sıfırla",
        "work_btn": "25dk Çalış",
        "break_short_btn": "5dk Mola",
        "break_long_btn": "15dk Mola",
        "running": "Çalışıyor",
        "resume": "Devam Et",
        "congrats": "Tebrikler!",
        "work_done_msg": "Odaklanma seansınız başarıyla tamamlandı. Şimdi mola zamanı!",
        "break_done_title": "Mola Bitti",
        "break_done_msg": "Mola süreniz doldu. Tekrar odaklanmaya hazır mısınız?",
        "app_title": "AuraTask",
        "total_focus_time": "Toplam Odaklanma Süresi",
        "completed_pomodoros": "Tamamlanan Pomodoro",
        "last_7_days": "Son 7 Günlük Odaklanma Grafiği (Dakika)",
        "task_board": "📋 Görev Panosu",
        "analytics": "📈 Verimlilik Analizi",
        "app_subtitle": "Kişisel Odak ve Görev Yöneticisi",
        "summary_stats": "Özet İstatistikler",
        "today_focus": "Bugün Odaklanma: {} dk",
        "total_tasks": "Toplam Görev Sayısı: {}",
        "delete_title": "Görevi Sil",
        "delete_confirm": "Bu görevi kalıcı olarak silmek istediğinizden emin misiniz?",
        "clear_completed": "Tamamlananları Temizle",
        "all_priorities": "Tüm Öncelikler",
        "filter_priority": "Filtre:",
        "search_placeholder": "🔍 Görev ara...",
        "min": "dk",
        "sessions": "Seans",
        "m": "dk"
    },
    "es": {
        "todo": "Por Hacer",
        "doing": "En Progreso",
        "done": "Completado",
        "low": "Bajo",
        "medium": "Medio",
        "high": "Alto",
        "work": "TRABAJO",
        "break": "DESCANSO",
        "add_task": "Agregar Tarea",
        "edit_task": "Editar Tarea",
        "title": "Título",
        "description": "Descripción",
        "priority": "Prioridad",
        "tags_label": "Etiquetas (separadas por comas)",
        "tags_placeholder": "ej. interfaz, error, código",
        "title_empty_warning": "El campo de título no puede estar vacío.",
        "warning": "Advertencia",
        "cancel": "Cancelar",
        "save": "Guardar",
        "move_back": "Retroceder",
        "move_forward": "Avanzar",
        "edit": "Editar",
        "delete": "Eliminar",
        "add": "Agregar",
        "focus_timer": "Temporizador de Enfoque",
        "start": "Iniciar",
        "pause": "Pausar",
        "reset": "Restablecer",
        "work_btn": "Trabajo 25m",
        "break_short_btn": "Descanso 5m",
        "break_long_btn": "Descanso 15m",
        "running": "En marcha",
        "resume": "Reanudar",
        "congrats": "¡Felicitaciones!",
        "work_done_msg": "Su sesión de enfoque se ha completado. ¡Tiempo de descansar!",
        "break_done_title": "Descanso Terminado",
        "break_done_msg": "Su descanso ha terminado. ¿Listo para enfocarse de nuevo?",
        "app_title": "AuraTask",
        "total_focus_time": "Tiempo Total de Enfoque",
        "completed_pomodoros": "Pomodoros Completados",
        "last_7_days": "Gráfico de Enfoque de los Últimos 7 Días (Minutos)",
        "task_board": "📋 Tablero de Tareas",
        "analytics": "📈 Análisis de Productividad",
        "app_subtitle": "Gestor de Enfoque y Tareas Personal",
        "summary_stats": "Estadísticas de Resumen",
        "today_focus": "Enfoque de Hoy: {} min",
        "total_tasks": "Total de Tareas: {}",
        "delete_title": "Eliminar Tarea",
        "delete_confirm": "¿Está seguro de que desea eliminar esta tarea permanentemente?",
        "clear_completed": "Limpiar Completados",
        "all_priorities": "Todas las Prioridades",
        "filter_priority": "Filtro:",
        "search_placeholder": "🔍 Buscar tareas...",
        "min": "min",
        "sessions": "Sesiones",
        "m": "m"
    }
}

class Localization:
    _lang = "en"

    @classmethod
    def init_locale(cls):
        sys_locale = QLocale.system().name() # e.g. "tr_TR", "en_US", "es_ES"
        prefix = sys_locale.split("_")[0].lower()
        if prefix in TRANSLATIONS:
            cls._lang = prefix
        else:
            cls._lang = "en"

    @classmethod
    def get(cls, key, *args):
        text = TRANSLATIONS[cls._lang].get(key, key)
        if args:
            return text.format(*args)
        return text

    @classmethod
    def lang(cls):
        return cls._lang

# Initialize immediately on import
Localization.init_locale()
