import locale
from PyQt6.QtCore import QLocale

TRANSLATIONS = {
    "en": {
        "todo": "To Do",
        "doing": "In Progress",
        "done": "Completed",
        "low": "Low",
        "medium": "Medium",
        "high": "High",
        "work": "WORK",
        "break": "BREAK",
        "add_task": "Add Task",
        "edit_task": "Edit Task",
        "title": "Title",
        "description": "Description",
        "priority": "Priority",
        "tags_label": "Tags (comma separated)",
        "tags_placeholder": "e.g. ui, bug, code",
        "title_empty_warning": "Title field cannot be empty.",
        "warning": "Warning",
        "cancel": "Cancel",
        "save": "Save",
        "move_back": "Move Back",
        "move_forward": "Move Forward",
        "edit": "Edit",
        "delete": "Delete",
        "add": "Add",
        "focus_timer": "Focus Timer",
        "start": "Start",
        "pause": "Pause",
        "reset": "Reset",
        "work_btn": "{}m Work",
        "break_short_btn": "{}m Break",
        "break_long_btn": "{}m Break",
        "running": "Running",
        "resume": "Resume",
        "congrats": "Congratulations!",
        "work_done_msg": "Your focus session is completed. Time for a break!",
        "break_done_title": "Break Finished",
        "break_done_msg": "Your break is over. Ready to focus again?",
        "app_title": "AuraTask",
        "total_focus_time": "Total Focus Time",
        "completed_pomodoros": "Completed Pomodoros",
        "last_7_days": "Last 7 Days Focus Chart (Minutes)",
        "task_board": "📋 Task Board",
        "analytics": "📈 Productivity Analytics",
        "app_subtitle": "Personal Focus & Task Manager",
        "summary_stats": "Summary Stats",
        "today_focus": "Today's Focus: {} min",
        "total_tasks": "Total Tasks: {}",
        "delete_title": "Delete Task",
        "delete_confirm": "Are you sure you want to permanently delete this task?",
        "clear_completed": "Clear Completed",
        "all_priorities": "All Priorities",
        "filter_priority": "Filter:",
        "search_placeholder": "🔍 Search tasks...",
        "min": "min",
        "sessions": "Sessions",
        "m": "m",
        "due_date": "Due Date",
        "has_due_date": "Set Due Date",
        "overdue": "Overdue",
        "focus_on_task": "Focus on Task:",
        "general_focus": "General Focus",
        "subtasks": "Subtasks",
        "add_subtask": "Add Subtask",
        "subtask_placeholder": "Subtask title...",
        "daily_goal": "Daily Goal Progress",
        "change_goal": "Set Daily Goal",
        "goal_minutes": "Goal (minutes)",
        "archive": "📁 Archive",
        "restore": "Restore",
        "perm_delete": "Delete Permanently",
        "sort_by": "Sort By:",
        "sort_date": "Date Created",
        "sort_priority": "Priority",
        "sort_due": "Due Date",
        "sort_focus": "Focus Time",
        "session_finished": "Session Finished",
        "show": "Show Window",
        "quit_app": "Quit Application",
        "running_in_bg_msg": "AuraTask is running in the background.",
        "change_total_focus": "Set Total Focus Time",
        "total_focus_minutes_label": "Total Focus (minutes)",
        "double_click_to_change_total_focus": "Double click to edit total focus time",
        "change_today_focus": "Set Today's Focus Time",
        "today_focus_minutes_label": "Today's Focus (minutes)",
        "double_click_to_change_today_focus": "Double click to edit today's focus time",
        "heatmap": "Focus Heatmap",
        "calendar": "Calendar View",
        "settings": "Settings",
        "theme": "Theme",
        "light_mode": "Light Mode",
        "dark_mode": "Dark Mode",
        "backup": "Backup & Data",
        "export_csv": "Export to CSV",
        "import_csv": "Import from CSV",
        "donut_chart": "Task Distribution",
        "shortcuts": "Keyboard Shortcuts",
        "tag_color": "Tag Color",
        "pomodoro_settings": "Timer Settings",
        "work_duration": "Work Duration (min)",
        "short_break": "Short Break (min)",
        "long_break": "Long Break (min)",
        "csv_id": "ID",
        "csv_title": "Title",
        "csv_status": "Status",
        "csv_priority": "Priority",
        
        # New keys
        "heatmap_title": "Last 12 Weeks Focus Heatmap",
        "calendar_header": "Monthly Calendar View",
        "calendar_tab": "Calendar",
        "settings_tab": "Settings",
        "settings_header": "Settings",
        "theme_section_title": "🎨 Theme",
        "theme_section_desc": "Choose the app's visual theme. Changes apply instantly.",
        "shortcuts_btn": "⌨  Shortcuts",
        "shortcuts_tooltip": "Keyboard Shortcuts",
        "backup_section_title": "💾 Data Backup",
        "backup_section_desc": "Export your tasks and stats or import from a backup.",
        "btn_export_json": " Export JSON",
        "btn_export_csv": " Export CSV",
        "btn_import_json": " Import JSON",
        "tooltip_export_json": "Export all tasks and stats as JSON",
        "tooltip_export_csv": "Export tasks as CSV",
        "tooltip_import_json": "Import tasks from a JSON backup",
        "donut_task_dist": "Task Distribution",
        "donut_tag_focus": "Tag Focus Time",
        "donut_priority": "Priority",
        "donut_tag": "Tag Focus",
        "donut_other": "Other",
        "donut_tasks_unit": "tasks",
        "donut_time_unit": "min",
        "donut_high": "High",
        "donut_medium": "Medium",
        "donut_low": "Low",
        "shortcuts_dialog_title": "Keyboard Shortcuts",
        "shortcuts_dialog_header": "⌨  Keyboard Shortcuts",
        "shortcut_space": "Toggle Timer Start / Pause",
        "shortcut_ctrl_n": "Add New Task",
        "shortcut_ctrl_1": "Go to Task Board",
        "shortcut_ctrl_2": "Go to Analytics",
        "shortcut_ctrl_3": "Go to Calendar",
        "shortcut_ctrl_4": "Go to Archive",
        "shortcut_ctrl_5": "Go to Settings",
        "shortcut_ctrl_alt_c": "Archive Completed Tasks",
        "close": "Close",
        "tag_colors_title": "Tag Colors",
        "tag_colors_hint": "Select a color for each tag. Changes apply to all tasks.",
        "tag_color_reset_tooltip": "Reset to default color",
        "tag_colors_no_tags_title": "No Tags",
        "tag_colors_no_tags_msg": "Please enter tags in the tags field first, then choose colors.",
        "tag_colors_edit_tooltip": "Edit tag colors",
        "subtask_edit_tooltip": "Double click item to delete",
        "timer_double_click_tooltip": "Double click to customize duration",
        "timer_settings_title": "Timer Settings",
        "timer_settings_header": "Duration & Goal Settings",
        "timer_work_label": "Work Duration (Minutes):",
        "timer_short_break_label": "Short Break Duration (Minutes):",
        "timer_long_break_label": "Long Break Duration (Minutes):",
        "timer_daily_goal_label": "Daily Focus Goal (Minutes):",
        "timer_validation_error": "Please enter positive integers for all fields.",
        "timer_settings_tooltip": "Configure Timer Durations",
        "timer_customize_title": "Customize Duration",
        "timer_customize_label": "Focus/Break duration (minutes):",
        "subtask_edit_card_tooltip": "Double-click the edit button to modify subtask titles",
        "work_btn_fmt": "{}m Work",
        "break_btn_fmt": "{}m Break",
        "export_json_dialog_title": "Export as JSON",
        "export_json_filter": "JSON Files (*.json)",
        "export_csv_dialog_title": "Export as CSV",
        "export_csv_filter": "CSV Files (*.csv)",
        "import_json_dialog_title": "Import from JSON Backup",
        "import_json_filter": "JSON Files (*.json)",
        "export_success_title": "Success",
        "export_json_success": "Data exported successfully:\n{}",
        "export_csv_success": "Tasks exported as CSV:\n{}",
        "export_error_title": "Error",
        "export_json_error": "Export failed:\n{}",
        "export_csv_error": "CSV export failed:\n{}",
        "import_invalid_warning": "Invalid backup file: 'tasks' field not found.",
        "import_confirm_title": "Import Confirmation",
        "import_confirm_msg": "This will add {} tasks (existing data preserved).\nDo you want to continue?",
        "import_success": "{} new tasks imported successfully.",
        "import_error": "Import failed:\n{}",
        "csv_header_id": "ID",
        "csv_header_title": "Title",
        "csv_header_desc": "Description",
        "csv_header_priority": "Priority",
        "csv_header_status": "Status",
        "csv_header_tags": "Tags",
        "csv_header_due": "Due Date",
        "csv_header_focus": "Focus Time (min)",
        "csv_header_created": "Created At",
        "tag_colors_preset_turkuaz": "Turquoise",
        "tag_colors_preset_mor": "Purple",
        "tag_colors_preset_amber": "Amber",
        "tag_colors_preset_kirmizi": "Red",
        "tag_colors_preset_yesil": "Green",
        "tag_colors_preset_mavi": "Blue",
        "tag_colors_preset_pembe": "Pink",
        "tag_colors_preset_turuncu": "Orange",
        "tag_colors_preset_cyan": "Cyan",
        "tag_colors_preset_lime": "Lime",
        "tag_colors_preset_lavanta": "Lavender",
        "tag_colors_preset_gri": "Grey",
        "month_names": "January,February,March,April,May,June,July,August,September,October,November,December",
        "day_names": "Mon,Tue,Wed,Thu,Fri,Sat,Sun",
        "theme_default": "Default Dark",
        "theme_cyberpunk": "Cyberpunk Neon",
        "theme_nord": "Nordic Frost (Nord)",
        "theme_emerald": "Emerald Green (Emerald)"
    },
    "tr": {
        "todo": "Yapılacak",
        "doing": "Yapılıyor",
        "done": "Tamamlandı",
        "low": "Düşük",
        "medium": "Orta",
        "high": "Yüksek",
        "work": "ÇALIŞMA",
        "break": "MOLA",
        "add_task": "Görev Ekle",
        "edit_task": "Görevi Düzenle",
        "title": "Başlık",
        "description": "Açıklama",
        "priority": "Öncelik",
        "tags_label": "Etiketler (virgülle ayırın)",
        "tags_placeholder": "örn: arayüz, hata, kod",
        "title_empty_warning": "Başlık alanı boş bırakılamaz.",
        "warning": "Uyarı",
        "cancel": "İptal",
        "save": "Kaydet",
        "move_back": "Geri Al",
        "move_forward": "İlerlet",
        "edit": "Düzenle",
        "delete": "Sil",
        "add": "Ekle",
        "focus_timer": "Odak Zamanlayıcısı",
        "start": "Başlat",
        "pause": "Duraklat",
        "reset": "Sıfırla",
        "work_btn": "{}dk Çalış",
        "break_short_btn": "{}dk Mola",
        "break_long_btn": "{}dk Mola",
        "running": "Çalışıyor",
        "resume": "Devam Et",
        "congrats": "Tebrikler!",
        "work_done_msg": "Odaklanma seansınız başarıyla tamamlandı. Şimdi mola zamanı!",
        "break_done_title": "Mola Bitti",
        "break_done_msg": "Mola süreniz doldu. Tekrar odaklanmaya hazır mısınız?",
        "app_title": "AuraTask",
        "total_focus_time": "Toplam Odaklanma Süresi",
        "completed_pomodoros": "Tamamlanan Pomodoro",
        "last_7_days": "Son 7 Günlük Odaklanma Grafiği (Dakika)",
        "task_board": "📋 Görev Panosu",
        "analytics": "📈 Verimlilik Analizi",
        "app_subtitle": "Kişisel Odak ve Görev Yöneticisi",
        "summary_stats": "Özet İstatistikler",
        "today_focus": "Bugün Odaklanma: {} dk",
        "total_tasks": "Toplam Görev Sayısı: {}",
        "delete_title": "Görevi Sil",
        "delete_confirm": "Bu görevi kalıcı olarak silmek istediğinizden emin misiniz?",
        "clear_completed": "Tamamlananları Temizle",
        "all_priorities": "Tüm Öncelikler",
        "filter_priority": "Filtre:",
        "search_placeholder": "🔍 Görev ara...",
        "min": "dk",
        "sessions": "Seans",
        "m": "dk",
        "due_date": "Teslim Tarihi",
        "has_due_date": "Teslim Tarihi Belirle",
        "overdue": "Gecikti",
        "focus_on_task": "Göreve Odaklan:",
        "general_focus": "Genel Odaklanma",
        "subtasks": "Alt Görevler",
        "add_subtask": "Alt Görev Ekle",
        "subtask_placeholder": "Alt görev başlığı...",
        "daily_goal": "Günlük Hedef İlerlemesi",
        "change_goal": "Günlük Hedefi Ayarla",
        "goal_minutes": "Hedef (dakika)",
        "archive": "📁 Arşiv",
        "restore": "Geri Yükle",
        "perm_delete": "Kalıcı Olarak Sil",
        "sort_by": "Sıralama:",
        "sort_date": "Oluşturma Tarihi",
        "sort_priority": "Öncelik",
        "sort_due": "Teslim Tarihi",
        "sort_focus": "Odak Süresi",
        "session_finished": "Seans Bitti",
        "show": "Pencereyi Göster",
        "quit_app": "Uygulamadan Çık",
        "running_in_bg_msg": "AuraTask arka planda çalışmaya devam ediyor.",
        "change_total_focus": "Toplam Odaklanma Süresini Ayarla",
        "total_focus_minutes_label": "Toplam Odaklanma (dakika)",
        "double_click_to_change_total_focus": "Toplam odaklanma süresini düzenlemek için çift tıklayın",
        "change_today_focus": "Bugünkü Odaklanma Süresini Ayarla",
        "today_focus_minutes_label": "Bugün Odaklanma (dakika)",
        "double_click_to_change_today_focus": "Bugünkü odaklanma süresini düzenlemek için çift tıklayın",
        "heatmap": "Odaklanma Haritası",
        "calendar": "Takvim Görünümü",
        "settings": "Ayarlar",
        "theme": "Tema",
        "light_mode": "Açık Mod",
        "dark_mode": "Koyu Mod",
        "backup": "Yedekleme & Veri",
        "export_csv": "CSV Olarak Dışa Aktar",
        "import_csv": "CSV Olarak İçe Aktar",
        "donut_chart": "Görev Dağılımı",
        "shortcuts": "Klavye Kısayolları",
        "tag_color": "Etiket Rengi",
        "pomodoro_settings": "Zamanlayıcı Ayarları",
        "work_duration": "Çalışma Süresi (dk)",
        "short_break": "Kısa Mola (dk)",
        "long_break": "Uzun Mola (dk)",
        "csv_id": "ID",
        "csv_title": "Başlık",
        "csv_status": "Durum",
        "csv_priority": "Öncelik",
        
        # New keys
        "heatmap_title": "Son 12 Hafta Odaklanma Haritası",
        "calendar_header": "Aylık Takvim Görünümü",
        "calendar_tab": "Takvim",
        "settings_tab": "Ayarlar",
        "settings_header": "Ayarlar",
        "theme_section_title": "🎨 Tema",
        "theme_section_desc": "Uygulamanın görsel temasını seçin. Değişiklikler anında uygulanır.",
        "shortcuts_btn": "⌨  Kısayollar",
        "shortcuts_tooltip": "Klavye Kısayolları",
        "backup_section_title": "💾 Veri Yedekleme",
        "backup_section_desc": "Görevlerinizi ve istatistiklerinizi dışa aktarın ya da bir yedekten içe aktarın.",
        "btn_export_json": " JSON Dışa Aktar",
        "btn_export_csv": " CSV Dışa Aktar",
        "btn_import_json": " JSON İçe Al",
        "tooltip_export_json": "Tüm görevleri ve istatistikleri JSON olarak dışa aktar",
        "tooltip_export_csv": "Görevleri CSV olarak dışa aktar",
        "tooltip_import_json": "JSON yedekten görevleri içe aktar",
        "donut_task_dist": "Görev Dağılımı",
        "donut_tag_focus": "Etiket Odak Süresi",
        "donut_priority": "Öncelik",
        "donut_tag": "Etiket Odak",
        "donut_other": "Diğer",
        "donut_tasks_unit": "görev",
        "donut_time_unit": "dk",
        "donut_high": "Yüksek",
        "donut_medium": "Orta",
        "donut_low": "Düşük",
        "shortcuts_dialog_title": "Klavye Kısayolları",
        "shortcuts_dialog_header": "⌨  Klavye Kısayolları",
        "shortcut_space": "Zamanlayıcıyı Başlat / Durdur",
        "shortcut_ctrl_n": "Yeni Görev Ekle",
        "shortcut_ctrl_1": "Görev Panosuna Git",
        "shortcut_ctrl_2": "Analitiğe Git",
        "shortcut_ctrl_3": "Takvime Git",
        "shortcut_ctrl_4": "Arşive Git",
        "shortcut_ctrl_5": "Ayarlara Git",
        "shortcut_ctrl_alt_c": "Tamamlananları Arşivle",
        "close": "Kapat",
        "tag_colors_title": "Etiket Renkleri",
        "tag_colors_hint": "Her etiket için bir renk seç. Değişiklikler tüm görevlere uygulanır.",
        "tag_color_reset_tooltip": "Varsayılan renge sıfırla",
        "tag_colors_no_tags_title": "Etiket Yok",
        "tag_colors_no_tags_msg": "Önce etiket alanına etiket girin, sonra renk seçin.",
        "tag_colors_edit_tooltip": "Etiket renklerini düzenle",
        "subtask_edit_tooltip": "Silmek için çift tıklayın",
        "timer_double_click_tooltip": "Süreyi özelleştirmek için çift tıklayın",
        "timer_settings_title": "Zamanlayıcı Ayarları",
        "timer_settings_header": "Süre ve Hedef Ayarları",
        "timer_work_label": "Çalışma Süresi (Dakika):",
        "timer_short_break_label": "Kısa Mola Süresi (Dakika):",
        "timer_long_break_label": "Uzun Mola Süresi (Dakika):",
        "timer_daily_goal_label": "Günlük Hedef Odaklanma (Dakika):",
        "timer_validation_error": "Lütfen tüm alanlara pozitif tamsayı değerler girin.",
        "timer_settings_tooltip": "Zamanlayıcı Sürelerini Ayarla",
        "timer_customize_title": "Süreyi Özelleştir",
        "timer_customize_label": "Odaklanma/Mola süresi (dakika):",
        "subtask_edit_card_tooltip": "Alt görev başlıklarını düzenlemek için düzenle butonuna çift tıklayın",
        "work_btn_fmt": "{}dk Çalış",
        "break_btn_fmt": "{}dk Mola",
        "export_json_dialog_title": "JSON Olarak Dışa Aktar",
        "export_json_filter": "JSON Dosyaları (*.json)",
        "export_csv_dialog_title": "CSV Olarak Dışa Aktar",
        "export_csv_filter": "CSV Dosyaları (*.csv)",
        "import_json_dialog_title": "JSON Yedekten İçe Aktar",
        "import_json_filter": "JSON Dosyaları (*.json)",
        "export_success_title": "Başarılı",
        "export_json_success": "Veriler başarıyla dışa aktarıldı:\n{}",
        "export_csv_success": "Görevler CSV olarak dışa aktarıldı:\n{}",
        "export_error_title": "Hata",
        "export_json_error": "Dışa aktarma başarısız:\n{}",
        "export_csv_error": "CSV dışa aktarma başarısız:\n{}",
        "import_invalid_warning": "Geçersiz yedek dosyası: 'tasks' alanı bulunamadı.",
        "import_confirm_title": "İçe Aktarma Onayı",
        "import_confirm_msg": "Bu işlem {} görevi ekleyecek (mevcut veriler korunur).\nDevam etmek istiyor musunuz?",
        "import_success": "{} yeni görev başarıyla içe aktarıldı.",
        "import_error": "İçe aktarma başarısız:\n{}",
        "csv_header_id": "ID",
        "csv_header_title": "Başlık",
        "csv_header_desc": "Açıklama",
        "csv_header_priority": "Öncelik",
        "csv_header_status": "Durum",
        "csv_header_tags": "Etiketler",
        "csv_header_due": "Son Tarih",
        "csv_header_focus": "Odak Süresi (dk)",
        "csv_header_created": "Oluşturma Tarihi",
        "tag_colors_preset_turkuaz": "Turkuaz",
        "tag_colors_preset_mor": "Mor",
        "tag_colors_preset_amber": "Amber",
        "tag_colors_preset_kirmizi": "Kırmızı",
        "tag_colors_preset_yesil": "Yeşil",
        "tag_colors_preset_mavi": "Mavi",
        "tag_colors_preset_pembe": "Pembe",
        "tag_colors_preset_turuncu": "Turuncu",
        "tag_colors_preset_cyan": "Cyan",
        "tag_colors_preset_lime": "Lime",
        "tag_colors_preset_lavanta": "Lavanta",
        "tag_colors_preset_gri": "Gri",
        "month_names": "Ocak,Şubat,Mart,Nisan,Mayıs,Haziran,Temmuz,Ağustos,Eylül,Ekim,Kasım,Aralık",
        "day_names": "Pzt,Sal,Çar,Per,Cum,Cmt,Paz",
        "theme_default": "Varsayılan Koyu",
        "theme_cyberpunk": "Cyberpunk Neon",
        "theme_nord": "Kutup Rüzgarı (Nord)",
        "theme_emerald": "Zümrüt Yeşili (Emerald)"
    },
    "es": {
        "todo": "Por Hacer",
        "doing": "En Progreso",
        "done": "Completado",
        "low": "Bajo",
        "medium": "Medio",
        "high": "Alto",
        "work": "TRABAJO",
        "break": "DESCANSO",
        "add_task": "Agregar Tarea",
        "edit_task": "Editar Tarea",
        "title": "Título",
        "description": "Descripción",
        "priority": "Prioridad",
        "tags_label": "Etiquetas (separadas por comas)",
        "tags_placeholder": "ej. interfaz, error, código",
        "title_empty_warning": "El campo de título no puede estar vacío.",
        "warning": "Advertencia",
        "cancel": "Cancelar",
        "save": "Guardar",
        "move_back": "Retroceder",
        "move_forward": "Avanzar",
        "edit": "Editar",
        "delete": "Eliminar",
        "add": "Agregar",
        "focus_timer": "Temporizador de Enfoque",
        "start": "Iniciar",
        "pause": "Pausar",
        "reset": "Restablecer",
        "work_btn": "Trabajo {}m",
        "break_short_btn": "Descanso {}m",
        "break_long_btn": "Descanso {}m",
        "running": "En marcha",
        "resume": "Reanudar",
        "congrats": "¡Felicitaciones!",
        "work_done_msg": "Su sesión de enfoque se ha completado. ¡Tiempo de descansar!",
        "break_done_title": "Descanso Terminado",
        "break_done_msg": "Su descanso ha terminado. ¿Listo para enfocarse de nuevo?",
        "app_title": "AuraTask",
        "total_focus_time": "Tiempo Total de Enfoque",
        "completed_pomodoros": "Pomodoros Completados",
        "last_7_days": "Gráfico de Enfoque de los Últimos 7 Días (Minutos)",
        "task_board": "📋 Tablero de Tareas",
        "analytics": "📈 Análisis de Productividad",
        "app_subtitle": "Gestor de Enfoque y Tareas Personal",
        "summary_stats": "Estadísticas de Resumen",
        "today_focus": "Enfoque de Hoy: {} min",
        "total_tasks": "Total de Tareas: {}",
        "delete_title": "Eliminar Tarea",
        "delete_confirm": "¿Está seguro de que desea eliminar esta tarea permanentemente?",
        "clear_completed": "Limpiar Completados",
        "all_priorities": "Todas las Prioridades",
        "filter_priority": "Filtro:",
        "search_placeholder": "🔍 Buscar tareas...",
        "min": "min",
        "sessions": "Sesiones",
        "m": "m",
        "due_date": "Fecha de Vencimiento",
        "has_due_date": "Establecer Fecha",
        "overdue": "Vencido",
        "focus_on_task": "Enfoque en Tarea:",
        "general_focus": "Enfoque General",
        "subtasks": "Subtareas",
        "add_subtask": "Agregar Subtarea",
        "subtask_placeholder": "Título de subtarea...",
        "daily_goal": "Progreso del Objetivo Diario",
        "change_goal": "Establecer Objetivo Diario",
        "goal_minutes": "Objetivo (minutos)",
        "archive": "📁 Archivo",
        "restore": "Restaurar",
        "perm_delete": "Eliminar Permanentemente",
        "sort_by": "Ordenar Por:",
        "sort_date": "Fecha de Creación",
        "sort_priority": "Prioridad",
        "sort_due": "Fecha de Vencimiento",
        "sort_focus": "Tiempo de Enfoque",
        "session_finished": "Sesión Terminada",
        "show": "Mostrar Ventana",
        "quit_app": "Salir de la Aplicación",
        "running_in_bg_msg": "AuraTask sigue ejecutándose en segundo plano.",
        "change_total_focus": "Ajustar Tiempo Total de Enfoque",
        "total_focus_minutes_label": "Enfoque Total (minutos)",
        "double_click_to_change_total_focus": "Haga doble clic para editar el tiempo total de enfoque",
        "change_today_focus": "Ajustar Tiempo de Enfoque de Hoy",
        "today_focus_minutes_label": "Enfoque de Hoy (minutos)",
        "double_click_to_change_today_focus": "Haga doble clic para editar el tiempo de enfoque de hoy",
        "heatmap": "Mapa de Calor de Enfoque",
        "calendar": "Vista de Calendario",
        "settings": "Configuración",
        "theme": "Tema",
        "light_mode": "Modo Claro",
        "dark_mode": "Modo Oscuro",
        "backup": "Respaldo y Datos",
        "export_csv": "Exportar a CSV",
        "import_csv": "Importar desde CSV",
        "donut_chart": "Distribución de Tareas",
        "shortcuts": "Atajos de Teclado",
        "tag_color": "Color de Etiqueta",
        "pomodoro_settings": "Configuración del Temporizador",
        "work_duration": "Duración de Trabajo (min)",
        "short_break": "Descanso Corto (min)",
        "long_break": "Descanso Largo (min)",
        "csv_id": "ID",
        "csv_title": "Título",
        "csv_status": "Estado",
        "csv_priority": "Prioridad",
        
        # New keys
        "heatmap_title": "Mapa de Calor de las Últimas 12 Semanas",
        "calendar_header": "Vista de Calendario Mensual",
        "calendar_tab": "Calendario",
        "settings_tab": "Ajustes",
        "settings_header": "Ajustes",
        "theme_section_title": "🎨 Tema",
        "theme_section_desc": "Elige el tema visual de la aplicación. Los cambios se aplican al instante.",
        "shortcuts_btn": "⌨  Atajos",
        "shortcuts_tooltip": "Atajos de Teclado",
        "backup_section_title": "💾 Copia de Seguridad",
        "backup_section_desc": "Exporta tus tareas y estadísticas o impórtalas desde una copia de seguridad.",
        "btn_export_json": " Exportar JSON",
        "btn_export_csv": " Exportar CSV",
        "btn_import_json": " Importar JSON",
        "tooltip_export_json": "Exportar todas las tareas y estadísticas como JSON",
        "tooltip_export_csv": "Exportar tareas como CSV",
        "tooltip_import_json": "Importar tareas desde una copia de seguridad JSON",
        "donut_task_dist": "Distribución de Tareas",
        "donut_tag_focus": "Tiempo de Enfoque por Etiqueta",
        "donut_priority": "Prioridad",
        "donut_tag": "Etiqueta",
        "donut_other": "Otros",
        "donut_tasks_unit": "tareas",
        "donut_time_unit": "min",
        "donut_high": "Alto",
        "donut_medium": "Medio",
        "donut_low": "Bajo",
        "shortcuts_dialog_title": "Atajos de Teclado",
        "shortcuts_dialog_header": "⌨  Atajos de Teclado",
        "shortcut_space": "Iniciar / Pausar Temporizador",
        "shortcut_ctrl_n": "Agregar Nueva Tarea",
        "shortcut_ctrl_1": "Ir al Tablero",
        "shortcut_ctrl_2": "Ir a Análisis",
        "shortcut_ctrl_3": "Ir al Calendario",
        "shortcut_ctrl_4": "Ir al Archivo",
        "shortcut_ctrl_5": "Ir a Ajustes",
        "shortcut_ctrl_alt_c": "Archivar Tareas Completadas",
        "close": "Cerrar",
        "tag_colors_title": "Colores de Etiqueta",
        "tag_colors_hint": "Selecciona un color para cada etiqueta. Los cambios aplican a todas las tareas.",
        "tag_color_reset_tooltip": "Restablecer al color predeterminado",
        "tag_colors_no_tags_title": "Sin Etiquetas",
        "tag_colors_no_tags_msg": "Primero ingrese etiquetas en el campo de etiquetas, luego elija colores.",
        "tag_colors_edit_tooltip": "Editar colores de etiquetas",
        "subtask_edit_tooltip": "Doble clic para eliminar",
        "timer_double_click_tooltip": "Doble clic para personalizar la duración",
        "timer_settings_title": "Configuración del Temporizador",
        "timer_settings_header": "Duración y Objetivo",
        "timer_work_label": "Duración de Trabajo (Minutos):",
        "timer_short_break_label": "Duración de Descanso Corto (Minutos):",
        "timer_long_break_label": "Duración de Descanso Largo (Minutos):",
        "timer_daily_goal_label": "Objetivo Diario de Enfoque (Minutos):",
        "timer_validation_error": "Por favor, ingrese valores enteros positivos en todos los campos.",
        "timer_settings_tooltip": "Configurar Duraciones del Temporizador",
        "timer_customize_title": "Personalizar Duración",
        "timer_customize_label": "Duración de enfoque/descanso (minutos):",
        "subtask_edit_card_tooltip": "Doble clic en el botón de edición para modificar títulos de subtareas",
        "work_btn_fmt": "{}m Trabajo",
        "break_btn_fmt": "{}m Descanso",
        "export_json_dialog_title": "Exportar como JSON",
        "export_json_filter": "Archivos JSON (*.json)",
        "export_csv_dialog_title": "Exportar como CSV",
        "export_csv_filter": "Archivos CSV (*.csv)",
        "import_json_dialog_title": "Importar desde Copia JSON",
        "import_json_filter": "Archivos JSON (*.json)",
        "export_success_title": "Éxito",
        "export_json_success": "Datos exportados exitosamente:\n{}",
        "export_csv_success": "Tareas exportadas como CSV:\n{}",
        "export_error_title": "Error",
        "export_json_error": "Exportación fallida:\n{}",
        "export_csv_error": "Exportación CSV fallida:\n{}",
        "import_invalid_warning": "Archivo de copia inválido: campo 'tasks' no encontrado.",
        "import_confirm_title": "Confirmación de Importación",
        "import_confirm_msg": "Esto agregará {} tareas (los datos existentes se conservan).\n¿Desea continuar?",
        "import_success": "{} nuevas tareas importadas exitosamente.",
        "import_error": "Importación fallida:\n{}",
        "csv_header_id": "ID",
        "csv_header_title": "Título",
        "csv_header_desc": "Descripción",
        "csv_header_priority": "Prioridad",
        "csv_header_status": "Estado",
        "csv_header_tags": "Etiquetas",
        "csv_header_due": "Fecha de Vencimiento",
        "csv_header_focus": "Tiempo de Enfoque (min)",
        "csv_header_created": "Fecha de Creación",
        "tag_colors_preset_turkuaz": "Turquesa",
        "tag_colors_preset_mor": "Morado",
        "tag_colors_preset_amber": "Ámbar",
        "tag_colors_preset_kirmizi": "Rojo",
        "tag_colors_preset_yesil": "Verde",
        "tag_colors_preset_mavi": "Azul",
        "tag_colors_preset_pembe": "Rosa",
        "tag_colors_preset_turuncu": "Naranja",
        "tag_colors_preset_cyan": "Cian",
        "tag_colors_preset_lime": "Lima",
        "tag_colors_preset_lavanta": "Lavanda",
        "tag_colors_preset_gri": "Gris",
        "month_names": "Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre",
        "day_names": "Lun,Mar,Mié,Jue,Vie,Sáb,Dom",
        "theme_default": "Oscuro Predeterminado",
        "theme_cyberpunk": "Cyberpunk Neón",
        "theme_nord": "Nordic Frost (Nord)",
        "theme_emerald": "Verde Esmeralda (Emerald)"
    }
}

class Localization:
    _lang = "en"

    @classmethod
    def init_locale(cls):
        sys_locale = QLocale.system().name() # e.g. "tr_TR", "en_US", "es_ES"
        prefix = sys_locale.split("_")[0].lower()
        if prefix in TRANSLATIONS:
            cls._lang = prefix
        else:
            cls._lang = "en"

    @classmethod
    def get(cls, key, *args):
        text = TRANSLATIONS[cls._lang].get(key, key)
        if args:
            return text.format(*args)
        return text

    @classmethod
    def lang(cls):
        return cls._lang

# Initialize immediately on import
Localization.init_locale()
